### ISSUE TITLE
Clarification on lines 222 and 223 in xspectrum1d.py

### ISSUE THREAD

**Issue by AlexaVillaume** [linetools/linetools#385]
Related to issue #222 in the PYPIT repo (https://github.com/PYPIT/PYPIT/issues/222) I was hoping to get clarification on block of code from 216-234 in xspectrum1d.py. Specifically, the purpose of the gdsigval and badsigval arrays.

I have one exposure where the gdsigval array is coming back empty and so the code fails on line 232. The spectrum for this exposure seems fine with pretty high S/N. What should I do about this?

**Comment by profxj** [comment]
These lines generate a masked array for the spectrum.  If you wish
to avoid this, use  masking='none'  when generating the XSpectrum1D object.
This probably should be the default approach in PYPIT.

**Comment by AlexaVillaume** [comment]
On line 408 of pypit/arload.py I set masking='none', so,

`    spec = XSpectrum1D.from_file(fname, exten=exten, masking='none', **rsp_kwargs)
`
However, I still get an an error when I try to run coadd_1dspec,

```
Traceback (most recent call last):
  File "/Users/alexa/anaconda/bin/pypit_coadd_1dspec", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alexa/PYPIT/bin/pypit_coadd_1dspec", line 11, in <module>
    coadd_1dspec.main(args)
  File "/Users/alexa/PYPIT/pypit/scripts/coadd_1dspec.py", line 101, in main
    spectra = arcoadd.load_spec(gdfiles, iextensions=extensions, extract=ex_value, flux=flux_value)
  File "/Users/alexa/PYPIT/pypit/arcoadd.py", line 518, in load_spec
    spectra = collate(spectra_list)
  File "/Users/alexa/linetools/linetools/spectra/utils.py", line 147, in collate
    maxpix = max(maxpix, spec.npix)
  File "/Users/alexa/linetools/linetools/spectra/xspectrum1d.py", line 408, in npix
    self.set_diagnostics()  # Need to re-run in case self.select changes
  File "/Users/alexa/linetools/linetools/spectra/xspectrum1d.py", line 440, in set_diagnostics
    self._wvmin = np.min(self.wavelength[gdpx])
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2356, in amin
    return amin(axis=axis, out=out)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1443, in min
    return self._wrap_function(np.min, axis, out=out, keepdims=keepdims)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1408, in _wrap_function
    value = function(self.view(np.ndarray), *args, **kwargs)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2359, in amin
    out=out, keepdims=keepdims)
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```
Are there more things I need to change to not do any masking?

**Comment by profxj** [comment]
I doubt this is a linetools issue.  Please bring to PYPIT.
